# Generated by Django 2.1.15 on 2020-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.CharField(max_length=20)),
                ('VLL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('V1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('V2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('V3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Amps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('A1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('A2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('A3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Freq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wavg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('W1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('W2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('W3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wh', models.FloatField()),
            ],
        ),
    ]
